AUDIO_SAMPLES = [
    "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
    "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
    "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
    "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
    "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
    "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
    "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3",
    "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3",
    "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3",
    "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-13.mp3",
    "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-14.mp3",
    "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-15.mp3",
]

TAMIL_SONGS = [
    ("Vaathi Coming", "Anirudh Ravichander", "Kollywood", 210),
    ("Rowdy Baby", "Dhanush, Dhee", "Kollywood", 226),
    ("Why This Kolaveri Di", "Dhanush, Anirudh", "Kollywood", 244),
    ("Kannaana Kanne", "David Kollangode", "Kollywood", 258),
    ("Arabic Kuthu", "Anirudh Ravichander", "Kollywood", 195),
    ("Vaathi Raid", "Anirudh Ravichander", "Kollywood", 200),
    ("Chithirai Sevvaanam", "Anirudh Ravichander", "Kollywood", 215),
    ("Enjoy Enjaami", "Dhee, Arivu", "Folk Fusion", 297),
    ("Nenjukkul Peidhidum", "A.R. Rahman", "Kollywood", 288),
    ("Kaathalae Kaathalae", "Anirudh Ravichander", "Kollywood", 232),
    ("Kutti Story", "Anirudh Ravichander", "Kollywood", 191),
    ("Chellamma", "Anirudh Ravichander", "Kollywood", 220),
    ("Munbe Vaa", "A.R. Rahman", "Kollywood", 292),
    ("Vinnaithaandi Varuvaayaa", "A.R. Rahman", "Kollywood", 305),
    ("Uyire Uyire", "A.R. Rahman", "Kollywood", 276),
    ("Anbe Sivam", "A.R. Rahman", "Kollywood", 261),
    ("Roja Jaaneman", "A.R. Rahman", "Kollywood", 268),
    ("Mukkala Muqabla", "A.R. Rahman", "Kollywood", 254),
    ("Pudhu Vellai Mazhai", "Ilaiyaraaja", "Kollywood", 289),
    ("Ilamai Idho Idho", "Ilaiyaraaja", "Kollywood", 247),
    ("Sundari Kannal Oru Sethi", "A.R. Rahman", "Kollywood", 264),
    ("Nenjinile", "Yuvan Shankar Raja", "Kollywood", 250),
    ("Oru Deivam Thantha Poove", "Yuvan Shankar Raja", "Kollywood", 275),
    ("Onaayum Aattukkuttiyum", "G.V. Prakash Kumar", "Kollywood", 233),
    ("Po Nee Po", "Vijay Yesudas", "Kollywood", 258),
    ("Yenda Puliyae", "Sam C.S.", "Kollywood", 202),
    ("Ratchasa Mamaney", "D. Imman", "Kollywood", 214),
    ("Marainthu Paartha Kanmaniye", "Sean Roldan", "Kollywood", 271),
    ("Nee Paartha Vizhigal", "Anirudh Ravichander", "Kollywood", 249),
    ("Adiyae", "Vishal Chandrashekhar", "Kollywood", 219),
    ("Thangamey", "Anirudh Ravichander", "Kollywood", 236),
    ("Idhu Vedikkai Kadhala", "Yuvan Shankar Raja", "Kollywood", 245),
    ("Vachindamma", "Anirudh Ravichander", "Kollywood", 208),
    ("Sarvam Thaala Mayam", "A.R. Rahman", "Kollywood", 262),
    ("Naan Pizhaipen", "Sam C.S.", "Kollywood", 230),
    ("Kadhale Kadhale", "Anirudh Ravichander", "Kollywood", 241),
    ("Maruvaarthai", "Sid Sriram", "Kollywood", 285),
    ("Adiye Kolluthe", "Hiphop Tamizha", "Kollywood", 218),
    ("Jimikki Ponnu (Tamil)", "Anirudh Ravichander", "Kollywood", 205),
    ("Mersalaayitten", "A.R. Rahman", "Kollywood", 256),
    ("Alaipayuthey", "A.R. Rahman", "Kollywood", 279),
    ("Snehidhane", "A.R. Rahman", "Kollywood", 267),
    ("Vaseegara", "Bombay Jayashri", "Kollywood", 253),
    ("Ovvoru Pookkalume", "Vijay Yesudas", "Kollywood", 244),
    ("Yaaro Ivan Yaaro", "Karthik", "Kollywood", 259),
    ("Nazriya Vaa", "Anirudh Ravichander", "Kollywood", 217),
    ("Naan Un Nizhal", "Sean Roldan", "Kollywood", 238),
    ("Karuppu Vellai", "Sid Sriram", "Kollywood", 224),
    ("Thalli Pogathey (Tamil)", "Anirudh Ravichander", "Kollywood", 273),
    ("Simtaangaram", "Anirudh Ravichander", "Kollywood", 251),
    ("Rakita Rakita", "Anirudh Ravichander", "Kollywood", 199),
    ("Beat Le", "Anirudh Ravichander", "Kollywood", 213),
    ("Karuppi", "Anirudh Ravichander", "Kollywood", 227),
    ("Vaa Vaathi", "Anirudh Ravichander", "Kollywood", 206),
    ("Yenanga Pakkam", "Santhosh Narayanan", "Kollywood", 240),
    ("Semma Weightu", "Hiphop Tamizha", "Kollywood", 198),
    ("Chumma Kizhi", "Santhosh Narayanan", "Kollywood", 216),
    ("Verithanam", "Anirudh Ravichander", "Kollywood", 223),
    ("Marana Mass", "Anirudh Ravichander", "Kollywood", 210),
    ("Dandanakka", "D. Imman", "Kollywood", 195),
]

OTHER_LANGUAGE_SONGS = [
    ("Blinding Lights", "The Weeknd", "Pop", 200),
    ("Levitating", "Dua Lipa", "Pop", 203),
    ("Shape of You", "Ed Sheeran", "Pop", 234),
    ("Bohemian Rhapsody", "Queen", "Rock", 354),
    ("Uptown Funk", "Bruno Mars", "Funk", 270),
    ("Someone Like You", "Adele", "Soul", 285),
    ("Jimikki Kammal", "Zia Ul Haq", "Malayalam", 232),
    ("Butta Bomma", "Armaan Malik", "Telugu", 213),
    ("Ramuloo Ramulaa", "Anurag Kulkarni", "Telugu", 225),
    ("Srivalli", "Sid Sriram", "Telugu", 248),
    ("Naatu Naatu", "Rahul Sipligunj, Kaala Bhairava", "Telugu", 227),
    ("Kabhi Khushi Kabhie Gham", "Alka Yagnik", "Hindi", 296),
    ("Kal Ho Naa Ho", "Sonu Nigam", "Hindi", 297),
    ("Tum Hi Ho", "Arijit Singh", "Hindi", 262),
    ("Kesariya", "Arijit Singh", "Hindi", 268),
    ("Apna Time Aayega", "Ranveer Singh, DIVINE", "Hindi", 214),
    ("Despacito", "Luis Fonsi", "Latin Pop", 229),
    ("Shape of My Heart", "Sting", "Pop Rock", 236),
    ("Perfect", "Ed Sheeran", "Pop", 263),
    ("Counting Stars", "OneRepublic", "Pop Rock", 257),
]


def build_song_objects():
    songs = []
    idx = 0
    for title, artist, genre, duration in TAMIL_SONGS + OTHER_LANGUAGE_SONGS:
        audio_url = AUDIO_SAMPLES[idx % len(AUDIO_SAMPLES)]
        songs.append({
            "title": title,
            "artist": artist,
            "genre": genre,
            "duration": duration,
            "audio_url": audio_url,
        })
        idx += 1
    return songs